
name: auto-testing
on: push
    # paths:
    #       - vertex/trainer/task.py
jobs:
  run:
    runs-on: [ubuntu-latest]
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
   
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install CML
        uses: iterative/setup-cml@v1
        
      - name: Install DVC
        uses: iterative/setup-dvc@v1
        with:
          version: '1.0.1'

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Run the test
          pip install -r app/requirements.txt
          python git_test.py
          
         
          echo "## Workspace vs. Main" > report.md
          git fetch --prune
          #dvc metrics diff main --targets vertex/test_score.json --show-md >> report.md
          dvc metrics diff main --targets test_score.json --show-md >> report.md
          
          # Send it!
          cml comment create report.md
        

          
